/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Portero;

import DTO.EstudianteRegistroDTO;
import dominios.ComputadoraDominio;
import dominios.EstatusComputadora;
import excepciones.NegocioException;
import fachada.IComputadoraFachada;
import fachada.implementaciones.ComputadoraFachada;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Image;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Camila Zubía
 */
public class SeleccionComputadoraFrm extends javax.swing.JFrame {

    IComputadoraFachada fachada;
    List<ComputadoraDominio> computadoras;
    InicioSesionFrm iniciarSesion;
    EstudianteRegistroDTO estudianteRegistrado;
    
    /**
     * Creates new form SeleccionComputadoraFrm
     * @throws excepciones.NegocioException
     */
    public SeleccionComputadoraFrm(InicioSesionFrm iniciarSesion, EstudianteRegistroDTO estudianteRegistrado) throws NegocioException {
        this.fachada = new ComputadoraFachada();
        this.computadoras = fachada.listarComputadoras();
        this.iniciarSesion = iniciarSesion;
        this.estudianteRegistrado = estudianteRegistrado;
        initComponents();
        imprimirComputadoras(computadoras);
    }
    
    
    private void imprimirComputadoras(List<ComputadoraDominio> computadoras){
        panelComputadoras.removeAll();
        panelComputadoras.setLayout(new FlowLayout(FlowLayout.LEFT, 10, 10));
        
        for (ComputadoraDominio c : computadoras) {
           JPanel panelCompu = new JPanel();
           panelCompu.setLayout(new BoxLayout(panelCompu, BoxLayout.Y_AXIS));
           panelCompu.setPreferredSize(new Dimension(50, 80));
           panelCompu.setBackground(Color.WHITE);
           String rutaImagen = null;
            if (c.getEstatus() == EstatusComputadora.DISPONIBLE) {
                rutaImagen = "/compuVerde.png";
            }else if (c.getEstatus() == EstatusComputadora.APARTADA) {
                rutaImagen = "/compuRoja.png";
            }
            ImageIcon icono = new ImageIcon(getClass().getResource(rutaImagen));
            Image imagenEscalada = icono.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
            JLabel lblImagen = new JLabel(new ImageIcon(imagenEscalada));
            lblImagen.setAlignmentX(Component.CENTER_ALIGNMENT);

            JLabel lblNumero = new JLabel(c.getNumero());
            lblNumero.setFont(new Font("Arial", Font.BOLD, 14));
            lblNumero.setForeground(Color.BLACK);
            lblNumero.setAlignmentX(Component.CENTER_ALIGNMENT);

            panelCompu.add(lblImagen);
            panelCompu.add(Box.createVerticalStrut(5));
            panelCompu.add(lblNumero);
            
            panelComputadoras.add(panelCompu);
        }
        panelComputadoras.revalidate();
        panelComputadoras.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtFieldNumero = new javax.swing.JTextField();
        lblTiempo = new javax.swing.JLabel();
        comboBoxTiempo = new javax.swing.JComboBox<>();
        panelComputadoras = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 109, 182));

        panelFondo.setBackground(new java.awt.Color(186, 215, 235));
        panelFondo.setForeground(new java.awt.Color(255, 255, 255));
        panelFondo.setPreferredSize(new java.awt.Dimension(1077, 630));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(4, 109, 181));
        lblTitulo.setText("SELECCIONAR COMPUTADORA");

        lblNumero.setBackground(new java.awt.Color(255, 255, 255));
        lblNumero.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(4, 109, 181));
        lblNumero.setText("Número de computadora:");

        txtFieldNumero.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtFieldNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTiempo.setBackground(new java.awt.Color(255, 255, 255));
        lblTiempo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblTiempo.setForeground(new java.awt.Color(4, 109, 181));
        lblTiempo.setText("Tiempo de uso:");

        comboBoxTiempo.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        comboBoxTiempo.setForeground(new java.awt.Color(4, 109, 181));
        comboBoxTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxTiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboBoxTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTiempoActionPerformed(evt);
            }
        });

        panelComputadoras.setBackground(new java.awt.Color(255, 255, 255));
        panelComputadoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelComputadorasLayout = new javax.swing.GroupLayout(panelComputadoras);
        panelComputadoras.setLayout(panelComputadorasLayout);
        panelComputadorasLayout.setHorizontalGroup(
            panelComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        panelComputadorasLayout.setVerticalGroup(
            panelComputadorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siguiente.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anterior.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNumero)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267)
                                .addComponent(lblTiempo)))
                        .addGap(84, 84, 84)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addComponent(comboBoxTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblTitulo))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(panelComputadoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelComputadoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTiempo))
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        String texto = txtFieldNumero.getText();
        int numero = Integer.parseInt(texto);
        String tiempo = (String) comboBoxTiempo.getSelectedItem();
        new ConfirmarReservacionFrm(this, estudianteRegistrado, numero, tiempo).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        iniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboBoxTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTiempoActionPerformed
        comboBoxTiempo.getSelectedItem();
    }//GEN-LAST:event_comboBoxTiempoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JComboBox<String> comboBoxTiempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelComputadoras;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JTextField txtFieldNumero;
    // End of variables declaration//GEN-END:variables
}
