/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Administrador;

/**
 *
 * @author saula
 */
public class AgregarComputadoraFrm extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCompuFrm
     */
    public AgregarComputadoraFrm () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mySqlCheckBox = new javax.swing.JCheckBox();
        ipTxt = new javax.swing.JTextField();
        softwareLbl = new javax.swing.JLabel();
        ipLbl = new javax.swing.JLabel();
        laboratorioComboBox = new javax.swing.JComboBox<>();
        laboratorioLbl = new javax.swing.JLabel();
        numeroLbl = new javax.swing.JLabel();
        AutoCadCheckBox = new javax.swing.JCheckBox();
        photoshopCheckBox = new javax.swing.JCheckBox();
        wordCheckBox = new javax.swing.JCheckBox();
        netBeansCheckBox = new javax.swing.JCheckBox();
        numeroComputadoraTxt = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuPanelControl = new javax.swing.JMenu();
        menuGestionBloqueos = new javax.swing.JMenu();
        menuItemConsultarBloqueos = new javax.swing.JMenuItem();
        menuItemBloquearAcceso = new javax.swing.JMenuItem();
        menuGestionComputadoras = new javax.swing.JMenu();
        menuItemAgregarComputadoras = new javax.swing.JMenuItem();
        menuItemModificarComputadoras = new javax.swing.JMenuItem();
        menuGestionLaboratorios = new javax.swing.JMenu();
        menuItemAgregarLaboratorio = new javax.swing.JMenuItem();
        menuItemModificarLaboratorio = new javax.swing.JMenuItem();
        menuGenerarReportes = new javax.swing.JMenu();
        menuItemReporteCentroComputo = new javax.swing.JMenuItem();
        menuItemReporteCarreras = new javax.swing.JMenuItem();
        menuItemReporteBloqueos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(0, 109, 182));

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setText("AGREGAR COMPUTADORA");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 109, 181));

        agregarBtn.setText("AGREGAR");
        agregarBtn.setBackground(new java.awt.Color(0, 153, 255));
        agregarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        jPanel2.setOpaque(false);

        mySqlCheckBox.setText("MySQL WorkBench");
        mySqlCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        mySqlCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        ipTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        softwareLbl.setText("SOFTWARE:");
        softwareLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        softwareLbl.setForeground(new java.awt.Color(4, 109, 181));

        ipLbl.setText("IP:");
        ipLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        ipLbl.setForeground(new java.awt.Color(4, 109, 181));

        laboratorioComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        laboratorioComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        laboratorioLbl.setText("LABORATORIO:");
        laboratorioLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        laboratorioLbl.setForeground(new java.awt.Color(4, 109, 181));

        numeroLbl.setText("NUMERO:");
        numeroLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        numeroLbl.setForeground(new java.awt.Color(4, 109, 181));

        AutoCadCheckBox.setText("AutoCAD");
        AutoCadCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        AutoCadCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        photoshopCheckBox.setText("Photoshop");
        photoshopCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        photoshopCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        photoshopCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoshopCheckBoxActionPerformed(evt);
            }
        });

        wordCheckBox.setText("Word");
        wordCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        wordCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        netBeansCheckBox.setText("Apache NetBeans");
        netBeansCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        netBeansCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        numeroComputadoraTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(softwareLbl)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AutoCadCheckBox)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(photoshopCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(wordCheckBox)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mySqlCheckBox)
                            .addComponent(netBeansCheckBox)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numeroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(numeroComputadoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(laboratorioLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laboratorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ipLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(158, 158, 158)
                            .addComponent(ipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLbl)
                    .addComponent(numeroComputadoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipLbl))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laboratorioLbl)
                    .addComponent(laboratorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(softwareLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AutoCadCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(photoshopCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wordCheckBox))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(netBeansCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(mySqlCheckBox)
                        .addGap(3, 3, 3)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anterior.png"))); // NOI18N
        btnAnterior.setBackground(new java.awt.Color(186, 215, 235));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(243, 243, 243))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        menuPanelControl.setText("Panel de Control");

        menuGestionBloqueos.setText("Gestión de Bloqueos");

        menuItemConsultarBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemConsultarBloqueos.setText("Consultar Bloqueos");
        menuGestionBloqueos.add(menuItemConsultarBloqueos);

        menuItemBloquearAcceso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBloquearAcceso.setText("Bloquear Acceso");
        menuGestionBloqueos.add(menuItemBloquearAcceso);

        menuPanelControl.add(menuGestionBloqueos);

        menuGestionComputadoras.setText("Gestión de Computadoras");

        menuItemAgregarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarComputadoras.setText("Agregar Computadoras");
        menuGestionComputadoras.add(menuItemAgregarComputadoras);

        menuItemModificarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarComputadoras.setText("Modificar Computadoras");
        menuItemModificarComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarComputadorasActionPerformed(evt);
            }
        });
        menuGestionComputadoras.add(menuItemModificarComputadoras);

        menuPanelControl.add(menuGestionComputadoras);

        menuGestionLaboratorios.setText("Gestión de Laboratorios");

        menuItemAgregarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarLaboratorio.setText("Agregar Laboratorio");
        menuGestionLaboratorios.add(menuItemAgregarLaboratorio);

        menuItemModificarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarLaboratorio.setText("Modificar Laboratorio");
        menuItemModificarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarLaboratorioActionPerformed(evt);
            }
        });
        menuGestionLaboratorios.add(menuItemModificarLaboratorio);

        menuPanelControl.add(menuGestionLaboratorios);

        menuGenerarReportes.setText("Generar Reportes");

        menuItemReporteCentroComputo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCentroComputo.setText("Centro de Computo");
        menuGenerarReportes.add(menuItemReporteCentroComputo);

        menuItemReporteCarreras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCarreras.setText("Carreras");
        menuGenerarReportes.add(menuItemReporteCarreras);

        menuItemReporteBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteBloqueos.setText("Bloqueos");
        menuGenerarReportes.add(menuItemReporteBloqueos);

        menuPanelControl.add(menuGenerarReportes);

        menuBar.add(menuPanelControl);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void photoshopCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoshopCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoshopCheckBoxActionPerformed

    private void menuItemModificarComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarComputadorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarComputadorasActionPerformed

    private void menuItemModificarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarLaboratorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AutoCadCheckBox;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JLabel ipLbl;
    private javax.swing.JTextField ipTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> laboratorioComboBox;
    private javax.swing.JLabel laboratorioLbl;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGenerarReportes;
    private javax.swing.JMenu menuGestionBloqueos;
    private javax.swing.JMenu menuGestionComputadoras;
    private javax.swing.JMenu menuGestionLaboratorios;
    private javax.swing.JMenuItem menuItemAgregarComputadoras;
    private javax.swing.JMenuItem menuItemAgregarLaboratorio;
    private javax.swing.JMenuItem menuItemBloquearAcceso;
    private javax.swing.JMenuItem menuItemConsultarBloqueos;
    private javax.swing.JMenuItem menuItemModificarComputadoras;
    private javax.swing.JMenuItem menuItemModificarLaboratorio;
    private javax.swing.JMenuItem menuItemReporteBloqueos;
    private javax.swing.JMenuItem menuItemReporteCarreras;
    private javax.swing.JMenuItem menuItemReporteCentroComputo;
    private javax.swing.JMenu menuPanelControl;
    private javax.swing.JCheckBox mySqlCheckBox;
    private javax.swing.JCheckBox netBeansCheckBox;
    private javax.swing.JTextField numeroComputadoraTxt;
    private javax.swing.JLabel numeroLbl;
    private javax.swing.JCheckBox photoshopCheckBox;
    private javax.swing.JLabel softwareLbl;
    private javax.swing.JCheckBox wordCheckBox;
    // End of variables declaration//GEN-END:variables
}
