/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Administrador;

/**
 *
 * @author saula
 */
public class ConsultarBloqueosFrm extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarBloqueosFrm
     */
    public ConsultarBloqueosFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buscadorTxt = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        btnPaginadoAnterior = new javax.swing.JButton();
        btnPaginadoSiguiente = new javax.swing.JButton();
        paginaLbl = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPanelControl = new javax.swing.JMenu();
        menuGestionBloqueos = new javax.swing.JMenu();
        menuItemConsultarBloqueos = new javax.swing.JMenuItem();
        menuItemBloquearAcceso = new javax.swing.JMenuItem();
        menuGestionComputadoras = new javax.swing.JMenu();
        menuItemAgregarComputadoras = new javax.swing.JMenuItem();
        menuItemModificarComputadoras = new javax.swing.JMenuItem();
        menuGestionLaboratorios = new javax.swing.JMenu();
        menuItemAgregarLaboratorio = new javax.swing.JMenuItem();
        menuItemModificarLaboratorio = new javax.swing.JMenuItem();
        menuGenerarReportes = new javax.swing.JMenu();
        menuItemReporteCentroComputo = new javax.swing.JMenuItem();
        menuItemReporteCarreras = new javax.swing.JMenuItem();
        menuItemReporteBloqueos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(0, 109, 182));

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setText("CONSULTAR BLOQUEOS");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 109, 181));

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anterior.png"))); // NOI18N
        btnAnterior.setBackground(new java.awt.Color(186, 215, 235));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "MOTIVO", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBuscar.setText("BUSCAR");
        btnBuscar.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        consultarBtn.setText("CONSULTAR");
        consultarBtn.setBackground(new java.awt.Color(0, 153, 255));
        consultarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        btnPaginadoAnterior.setText("Anterior");
        btnPaginadoAnterior.setBackground(new java.awt.Color(0, 153, 255));

        btnPaginadoSiguiente.setText("Siguiente");
        btnPaginadoSiguiente.setBackground(new java.awt.Color(0, 153, 255));
        btnPaginadoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginadoSiguienteActionPerformed(evt);
            }
        });

        paginaLbl.setText("Página ");
        paginaLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        paginaLbl.setForeground(new java.awt.Color(4, 109, 181));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPaginadoAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaginadoSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paginaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428)
                        .addComponent(consultarBtn))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(btnBuscar)
                            .addGap(113, 113, 113)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPaginadoAnterior)
                        .addComponent(btnPaginadoSiguiente)
                        .addComponent(paginaLbl))))
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuPanelControl.setText("Panel de Control");

        menuGestionBloqueos.setText("Gestión de Bloqueos");

        menuItemConsultarBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemConsultarBloqueos.setText("Consultar Bloqueos");
        menuGestionBloqueos.add(menuItemConsultarBloqueos);

        menuItemBloquearAcceso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBloquearAcceso.setText("Bloquear Acceso");
        menuGestionBloqueos.add(menuItemBloquearAcceso);

        menuPanelControl.add(menuGestionBloqueos);

        menuGestionComputadoras.setText("Gestión de Computadoras");

        menuItemAgregarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarComputadoras.setText("Agregar Computadoras");
        menuGestionComputadoras.add(menuItemAgregarComputadoras);

        menuItemModificarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarComputadoras.setText("Modificar Computadoras");
        menuItemModificarComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarComputadorasActionPerformed(evt);
            }
        });
        menuGestionComputadoras.add(menuItemModificarComputadoras);

        menuPanelControl.add(menuGestionComputadoras);

        menuGestionLaboratorios.setText("Gestión de Laboratorios");

        menuItemAgregarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarLaboratorio.setText("Agregar Laboratorio");
        menuGestionLaboratorios.add(menuItemAgregarLaboratorio);

        menuItemModificarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarLaboratorio.setText("Modificar Laboratorio");
        menuItemModificarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarLaboratorioActionPerformed(evt);
            }
        });
        menuGestionLaboratorios.add(menuItemModificarLaboratorio);

        menuPanelControl.add(menuGestionLaboratorios);

        menuGenerarReportes.setText("Generar Reportes");

        menuItemReporteCentroComputo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCentroComputo.setText("Centro de Computo");
        menuGenerarReportes.add(menuItemReporteCentroComputo);

        menuItemReporteCarreras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCarreras.setText("Carreras");
        menuGenerarReportes.add(menuItemReporteCarreras);

        menuItemReporteBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteBloqueos.setText("Bloqueos");
        menuGenerarReportes.add(menuItemReporteBloqueos);

        menuPanelControl.add(menuGenerarReportes);

        menuBar.add(menuPanelControl);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnPaginadoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginadoSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaginadoSiguienteActionPerformed

    private void menuItemModificarComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarComputadorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarComputadorasActionPerformed

    private void menuItemModificarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarLaboratorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPaginadoAnterior;
    private javax.swing.JButton btnPaginadoSiguiente;
    private javax.swing.JTextField buscadorTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGenerarReportes;
    private javax.swing.JMenu menuGestionBloqueos;
    private javax.swing.JMenu menuGestionComputadoras;
    private javax.swing.JMenu menuGestionLaboratorios;
    private javax.swing.JMenuItem menuItemAgregarComputadoras;
    private javax.swing.JMenuItem menuItemAgregarLaboratorio;
    private javax.swing.JMenuItem menuItemBloquearAcceso;
    private javax.swing.JMenuItem menuItemConsultarBloqueos;
    private javax.swing.JMenuItem menuItemModificarComputadoras;
    private javax.swing.JMenuItem menuItemModificarLaboratorio;
    private javax.swing.JMenuItem menuItemReporteBloqueos;
    private javax.swing.JMenuItem menuItemReporteCarreras;
    private javax.swing.JMenuItem menuItemReporteCentroComputo;
    private javax.swing.JMenu menuPanelControl;
    private javax.swing.JLabel paginaLbl;
    // End of variables declaration//GEN-END:variables
}
