/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Administrador;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.border.Border;

/**
 *
 * @author saula
 */
public class FrameControl extends javax.swing.JFrame {

    /**
     * Creates new form FrameControl
     */
    public FrameControl() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelImagenItson = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPanelControl = new javax.swing.JMenu();
        menuGestionBloqueos = new javax.swing.JMenu();
        menuItemConsultarBloqueos = new javax.swing.JMenuItem();
        menuItemBloquearAcceso = new javax.swing.JMenuItem();
        menuItemConsultarComputadoras = new javax.swing.JMenuItem();
        menuGestionLaboratorios = new javax.swing.JMenu();
        menuItemAgregarLaboratorio = new javax.swing.JMenuItem();
        menuItemModificarLaboratorio = new javax.swing.JMenuItem();
        menuGenerarReportes = new javax.swing.JMenu();
        menuItemReporteCentroComputo = new javax.swing.JMenuItem();
        menuItemReporteCarreras = new javax.swing.JMenuItem();
        menuItemReporteBloqueos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setForeground(new java.awt.Color(186, 215, 235));

        labelImagenItson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITSON_azul.png"))); // NOI18N

        jLabel2.setText("BIENVENIDO");
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 109, 181));
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(357, 357, 357))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(labelImagenItson, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(labelImagenItson, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        menuPanelControl.setText("Panel de Control");

        menuGestionBloqueos.setText("Gestión de Bloqueos");

        menuItemConsultarBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemConsultarBloqueos.setText("Consultar Bloqueos");
        menuItemConsultarBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarBloqueosActionPerformed(evt);
            }
        });
        menuGestionBloqueos.add(menuItemConsultarBloqueos);

        menuItemBloquearAcceso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBloquearAcceso.setText("Bloquear Acceso");
        menuItemBloquearAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBloquearAccesoActionPerformed(evt);
            }
        });
        menuGestionBloqueos.add(menuItemBloquearAcceso);

        menuPanelControl.add(menuGestionBloqueos);

        menuItemConsultarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemConsultarComputadoras.setText("Consultar Computadoras");
        menuItemConsultarComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarComputadorasActionPerformed(evt);
            }
        });
        menuPanelControl.add(menuItemConsultarComputadoras);

        menuGestionLaboratorios.setText("Gestión de Laboratorios");

        menuItemAgregarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarLaboratorio.setText("Agregar Laboratorio");
        menuItemAgregarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAgregarLaboratorioActionPerformed(evt);
            }
        });
        menuGestionLaboratorios.add(menuItemAgregarLaboratorio);

        menuItemModificarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarLaboratorio.setText("Modificar Laboratorio");
        menuItemModificarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarLaboratorioActionPerformed(evt);
            }
        });
        menuGestionLaboratorios.add(menuItemModificarLaboratorio);

        menuPanelControl.add(menuGestionLaboratorios);

        menuGenerarReportes.setText("Generar Reportes");

        menuItemReporteCentroComputo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCentroComputo.setText("Centro de Computo");
        menuItemReporteCentroComputo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReporteCentroComputoActionPerformed(evt);
            }
        });
        menuGenerarReportes.add(menuItemReporteCentroComputo);

        menuItemReporteCarreras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCarreras.setText("Carreras");
        menuItemReporteCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReporteCarrerasActionPerformed(evt);
            }
        });
        menuGenerarReportes.add(menuItemReporteCarreras);

        menuItemReporteBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteBloqueos.setText("Bloqueos");
        menuItemReporteBloqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemReporteBloqueosActionPerformed(evt);
            }
        });
        menuGenerarReportes.add(menuItemReporteBloqueos);

        menuPanelControl.add(menuGenerarReportes);

        menuBar.add(menuPanelControl);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemModificarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarLaboratorioActionPerformed

    private void menuItemConsultarComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarComputadorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConsultarComputadorasActionPerformed

    private void menuItemConsultarBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarBloqueosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConsultarBloqueosActionPerformed

    private void menuItemBloquearAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBloquearAccesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBloquearAccesoActionPerformed

    private void menuItemAgregarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAgregarLaboratorioActionPerformed
        PanelAgregarLaboratorio panel = new PanelAgregarLaboratorio();
        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }//GEN-LAST:event_menuItemAgregarLaboratorioActionPerformed

    private void menuItemReporteCentroComputoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReporteCentroComputoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemReporteCentroComputoActionPerformed

    private void menuItemReporteCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReporteCarrerasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemReporteCarrerasActionPerformed

    private void menuItemReporteBloqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemReporteBloqueosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemReporteBloqueosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImagenItson;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGenerarReportes;
    private javax.swing.JMenu menuGestionBloqueos;
    private javax.swing.JMenu menuGestionLaboratorios;
    private javax.swing.JMenuItem menuItemAgregarLaboratorio;
    private javax.swing.JMenuItem menuItemBloquearAcceso;
    private javax.swing.JMenuItem menuItemConsultarBloqueos;
    private javax.swing.JMenuItem menuItemConsultarComputadoras;
    private javax.swing.JMenuItem menuItemModificarLaboratorio;
    private javax.swing.JMenuItem menuItemReporteBloqueos;
    private javax.swing.JMenuItem menuItemReporteCarreras;
    private javax.swing.JMenuItem menuItemReporteCentroComputo;
    private javax.swing.JMenu menuPanelControl;
    // End of variables declaration//GEN-END:variables
}
