/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.Administrador;

/**
 *
 * @author adell
 */
public class MenuFrm extends javax.swing.JFrame {

    /**
     * Creates new form menuFrm
     */
    public MenuFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        labelImagenItson = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuPanelControl = new javax.swing.JMenu();
        menuGestionBloqueos = new javax.swing.JMenu();
        menuItemConsultarBloqueos = new javax.swing.JMenuItem();
        menuItemBloquearAcceso = new javax.swing.JMenuItem();
        menuGestionComputadoras = new javax.swing.JMenu();
        menuItemAgregarComputadoras = new javax.swing.JMenuItem();
        menuItemModificarComputadoras = new javax.swing.JMenuItem();
        menuGestionLaboratorios = new javax.swing.JMenu();
        menuItemAgregarLaboratorio = new javax.swing.JMenuItem();
        menuItemModificarLaboratorio = new javax.swing.JMenuItem();
        menuGenerarReportes = new javax.swing.JMenu();
        menuItemReporteCentroComputo = new javax.swing.JMenuItem();
        menuItemReporteCarreras = new javax.swing.JMenuItem();
        menuItemReporteBloqueos = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setForeground(new java.awt.Color(186, 215, 235));

        labelImagenItson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ITSON_azul.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 109, 181));
        jLabel2.setText("BIENVENIDO");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(357, 357, 357))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(labelImagenItson, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(labelImagenItson, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        menuPanelControl.setText("Panel de Control");

        menuGestionBloqueos.setText("Gestión de Bloqueos");

        menuItemConsultarBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemConsultarBloqueos.setText("Consultar Bloqueos");
        menuGestionBloqueos.add(menuItemConsultarBloqueos);

        menuItemBloquearAcceso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemBloquearAcceso.setText("Bloquear Acceso");
        menuGestionBloqueos.add(menuItemBloquearAcceso);

        menuPanelControl.add(menuGestionBloqueos);

        menuGestionComputadoras.setText("Gestión de Computadoras");

        menuItemAgregarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarComputadoras.setText("Agregar Computadoras");
        menuGestionComputadoras.add(menuItemAgregarComputadoras);

        menuItemModificarComputadoras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarComputadoras.setText("Modificar Computadoras");
        menuItemModificarComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarComputadorasActionPerformed(evt);
            }
        });
        menuGestionComputadoras.add(menuItemModificarComputadoras);

        menuPanelControl.add(menuGestionComputadoras);

        menuGestionLaboratorios.setText("Gestión de Laboratorios");

        menuItemAgregarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAgregarLaboratorio.setText("Agregar Laboratorio");
        menuGestionLaboratorios.add(menuItemAgregarLaboratorio);

        menuItemModificarLaboratorio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemModificarLaboratorio.setText("Modificar Laboratorio");
        menuItemModificarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarLaboratorioActionPerformed(evt);
            }
        });
        menuGestionLaboratorios.add(menuItemModificarLaboratorio);

        menuPanelControl.add(menuGestionLaboratorios);

        menuGenerarReportes.setText("Generar Reportes");

        menuItemReporteCentroComputo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCentroComputo.setText("Centro de Computo");
        menuGenerarReportes.add(menuItemReporteCentroComputo);

        menuItemReporteCarreras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteCarreras.setText("Carreras");
        menuGenerarReportes.add(menuItemReporteCarreras);

        menuItemReporteBloqueos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemReporteBloqueos.setText("Bloqueos");
        menuGenerarReportes.add(menuItemReporteBloqueos);

        menuPanelControl.add(menuGenerarReportes);

        menuBar.add(menuPanelControl);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemModificarComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarComputadorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarComputadorasActionPerformed

    private void menuItemModificarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemModificarLaboratorioActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JLabel labelImagenItson;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGenerarReportes;
    private javax.swing.JMenu menuGestionBloqueos;
    private javax.swing.JMenu menuGestionComputadoras;
    private javax.swing.JMenu menuGestionLaboratorios;
    private javax.swing.JMenuItem menuItemAgregarComputadoras;
    private javax.swing.JMenuItem menuItemAgregarLaboratorio;
    private javax.swing.JMenuItem menuItemBloquearAcceso;
    private javax.swing.JMenuItem menuItemConsultarBloqueos;
    private javax.swing.JMenuItem menuItemModificarComputadoras;
    private javax.swing.JMenuItem menuItemModificarLaboratorio;
    private javax.swing.JMenuItem menuItemReporteBloqueos;
    private javax.swing.JMenuItem menuItemReporteCarreras;
    private javax.swing.JMenuItem menuItemReporteCentroComputo;
    private javax.swing.JMenu menuPanelControl;
    // End of variables declaration//GEN-END:variables
}
