 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.Administrador;

import DTO.FiltroDTO;
import DTO.TablaBloqueosDTO;
import excepciones.NegocioException;
import fachada.IBloqueoFachada;
import fachada.implementaciones.BloqueoFachada;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saula
 */
public class PanelConsultarBloqueos extends javax.swing.JPanel {

    private final IBloqueoFachada bloqueoFachada;
    private int offset = 0;
    private final int limite = 5;
    public int id;

    public PanelConsultarBloqueos() {
        initComponents();
        this.bloqueoFachada = new BloqueoFachada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buscadorTxt = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        consultarBtn = new javax.swing.JButton();
        btnPaginadoAnterior = new javax.swing.JButton();
        btnPaginadoSiguiente = new javax.swing.JButton();
        paginaLbl = new javax.swing.JLabel();

        PanelFondo.setBackground(new java.awt.Color(0, 109, 182));

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 109, 181));
        jLabel1.setText("CONSULTAR BLOQUEOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ESTATUS", "MOTIVO", "FECHA"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBuscar.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        consultarBtn.setBackground(new java.awt.Color(0, 153, 255));
        consultarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        consultarBtn.setText("CONSULTAR");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });

        btnPaginadoAnterior.setBackground(new java.awt.Color(0, 153, 255));
        btnPaginadoAnterior.setText("Anterior");
        btnPaginadoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginadoAnteriorActionPerformed(evt);
            }
        });

        btnPaginadoSiguiente.setBackground(new java.awt.Color(0, 153, 255));
        btnPaginadoSiguiente.setText("Siguiente");
        btnPaginadoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginadoSiguienteActionPerformed(evt);
            }
        });

        paginaLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        paginaLbl.setForeground(new java.awt.Color(4, 109, 181));
        paginaLbl.setText("Página ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPaginadoAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPaginadoSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paginaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428)
                        .addComponent(consultarBtn))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(btnBuscar)
                            .addGap(113, 113, 113)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPaginadoAnterior)
                        .addComponent(btnPaginadoSiguiente)
                        .addComponent(paginaLbl))))
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            // TODO add your handling code here:
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleciona una fila");
            return;
        }

        if (filaSeleccionada != -1) {
            int idBloqueo = (int) jTable1.getValueAt(filaSeleccionada, 0);
            id = idBloqueo;
            try {
                bloqueoFachada.buscarPorId(idBloqueo);
                abrirPanelDesbloquear();
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, "error al cambiar acceso");
            }
        }
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void btnPaginadoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginadoAnteriorActionPerformed
        // TODO add your handling code here:
        if (offset - limite >= 0) {
            offset -= limite;
        } else {
            offset = 0;
        }
        try {
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPaginadoAnteriorActionPerformed

    private void btnPaginadoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginadoSiguienteActionPerformed
        // TODO add your handling code here:
        offset += limite;
        try {
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPaginadoSiguienteActionPerformed

    private void cargarTabla() throws NegocioException {
        try {
            String buscador = buscadorTxt.getText().trim();
            FiltroDTO filtro = new FiltroDTO(limite, offset, buscador);
            List<TablaBloqueosDTO> bloqueos = bloqueoFachada.buscarTabla(filtro);

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            for (TablaBloqueosDTO b : bloqueos) {
                Object[] fila = {
                    b.getIdBloqueo(),
                    b.isEstatus(),
                    b.getMotivo(),
                    b.getFechaBloqueo()
                };
                modelo.addRow(fila);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }

    private void abrirPanelDesbloquear() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);

        PanelDesbloquear panel = new PanelDesbloquear(id);


        frame.getContentPane().removeAll();
        frame.getContentPane().add(panel, BorderLayout.CENTER);
        frame.revalidate();
        frame.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPaginadoAnterior;
    private javax.swing.JButton btnPaginadoSiguiente;
    private javax.swing.JTextField buscadorTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel paginaLbl;
    // End of variables declaration//GEN-END:variables
}
