/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.Administrador;

import DTO.NuevaComputadoraDTO;
import dominios.ComputadoraDominio;
import dominios.EstatusComputadora;
import dominios.LaboratorioDominio;
import dominios.TipoComputadora;
import excepciones.NegocioException;
import fachada.IComputadoraFachada;
import fachada.ILaboratorioFachada;
import fachada.implementaciones.ComputadoraFachada;
import fachada.implementaciones.LaboratorioFachada;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author saula
 */
public class PanelAgregarComputadoras extends javax.swing.JPanel {

    private final IComputadoraFachada computadoraFachada;
    private final ILaboratorioFachada laboratorioFachada;
    
    public PanelAgregarComputadoras() {
        initComponents();
        this.computadoraFachada = new ComputadoraFachada();
        this.laboratorioFachada = new LaboratorioFachada();
        cargarLaboratorios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mySqlCheckBox = new javax.swing.JCheckBox();
        ipTxt = new javax.swing.JTextField();
        softwareLbl = new javax.swing.JLabel();
        ipLbl = new javax.swing.JLabel();
        numeroLbl = new javax.swing.JLabel();
        AutoCadCheckBox = new javax.swing.JCheckBox();
        photoshopCheckBox = new javax.swing.JCheckBox();
        wordCheckBox = new javax.swing.JCheckBox();
        netBeansCheckBox = new javax.swing.JCheckBox();
        numeroComputadoraTxt = new javax.swing.JTextField();
        laboratorioLbl = new javax.swing.JLabel();
        laboratorioComboBox = new javax.swing.JComboBox<>();
        laboratorioLbl1 = new javax.swing.JLabel();
        tipoComboBox1 = new javax.swing.JComboBox<>();
        btnAnterior = new javax.swing.JButton();

        PanelFondo.setBackground(new java.awt.Color(0, 109, 182));

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 109, 181));
        jLabel1.setText("AGREGAR COMPUTADORA");

        agregarBtn.setBackground(new java.awt.Color(0, 153, 255));
        agregarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        agregarBtn.setText("AGREGAR");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        jPanel2.setOpaque(false);

        mySqlCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        mySqlCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        mySqlCheckBox.setText("MySQL WorkBench");
        mySqlCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySqlCheckBoxActionPerformed(evt);
            }
        });

        ipTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        softwareLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        softwareLbl.setForeground(new java.awt.Color(4, 109, 181));
        softwareLbl.setText("SOFTWARE:");

        ipLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        ipLbl.setForeground(new java.awt.Color(4, 109, 181));
        ipLbl.setText("IP:");

        numeroLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        numeroLbl.setForeground(new java.awt.Color(4, 109, 181));
        numeroLbl.setText("NUMERO:");

        AutoCadCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        AutoCadCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        AutoCadCheckBox.setText("AutoCAD");
        AutoCadCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoCadCheckBoxActionPerformed(evt);
            }
        });

        photoshopCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        photoshopCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        photoshopCheckBox.setText("Photoshop");
        photoshopCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoshopCheckBoxActionPerformed(evt);
            }
        });

        wordCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        wordCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        wordCheckBox.setText("Word");
        wordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordCheckBoxActionPerformed(evt);
            }
        });

        netBeansCheckBox.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        netBeansCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        netBeansCheckBox.setText("Apache NetBeans");
        netBeansCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netBeansCheckBoxActionPerformed(evt);
            }
        });

        numeroComputadoraTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        laboratorioLbl.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        laboratorioLbl.setForeground(new java.awt.Color(4, 109, 181));
        laboratorioLbl.setText("LABORATORIO:");

        laboratorioComboBox.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        laboratorioLbl1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        laboratorioLbl1.setForeground(new java.awt.Color(4, 109, 181));
        laboratorioLbl1.setText("TIPO:");

        tipoComboBox1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tipoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PORTERO", "ESTUDIANTE" }));
        tipoComboBox1.setToolTipText("");
        tipoComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(laboratorioLbl1)
                        .addGap(152, 152, 152)
                        .addComponent(tipoComboBox1, 0, 194, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ipLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(laboratorioLbl)
                        .addGap(18, 18, 18)
                        .addComponent(laboratorioComboBox, 0, 194, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(softwareLbl)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(wordCheckBox)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(photoshopCheckBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(AutoCadCheckBox)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mySqlCheckBox)
                                    .addComponent(netBeansCheckBox))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(numeroLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numeroComputadoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laboratorioLbl)
                    .addComponent(laboratorioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laboratorioLbl1)
                    .addComponent(tipoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroLbl)
                    .addComponent(numeroComputadoraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipLbl)
                    .addComponent(ipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(softwareLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutoCadCheckBox)
                    .addComponent(netBeansCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoshopCheckBox)
                    .addComponent(mySqlCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wordCheckBox)
                .addContainerGap())
        );

        btnAnterior.setBackground(new java.awt.Color(186, 215, 235));
        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anterior.png"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        try {
            if (!validarCampos()) {
                return;
            }

            NuevaComputadoraDTO compu = construirNuevaComputadora();
            computadoraFachada.agregar(compu);
            JOptionPane.showMessageDialog(this, "Laboratorio registrado con éxito.");
            limpiarCampos();

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void photoshopCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoshopCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoshopCheckBoxActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        PanelConsultarComputadoras panelAnterior = new PanelConsultarComputadoras();

        frame.getContentPane().removeAll();
        frame.getContentPane().add(panelAnterior, BorderLayout.CENTER);
        frame.revalidate();
        frame.repaint();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void AutoCadCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoCadCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutoCadCheckBoxActionPerformed

    private void wordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordCheckBoxActionPerformed

    private void netBeansCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netBeansCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netBeansCheckBoxActionPerformed

    private void mySqlCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySqlCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mySqlCheckBoxActionPerformed

    private void tipoComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoComboBox1ActionPerformed

    
    private void cargarLaboratorios() {
        List<LaboratorioDominio> laboratorios;
        try {
            laboratorios = laboratorioFachada.obtenerLaboratorios();
            for (LaboratorioDominio l : laboratorios) {
                laboratorioComboBox.addItem(l.getNombre());
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR);
        }
    }
    
    private void limpiarCampos() {
        ipTxt.setText("");
        numeroComputadoraTxt.setText("");
        laboratorioComboBox.setSelectedIndex(0);
        tipoComboBox1.setSelectedIndex(0);
        wordCheckBox.setSelected(false);
        mySqlCheckBox.setSelected(false);
        netBeansCheckBox.setSelected(false);
        photoshopCheckBox.setSelected(false);
        AutoCadCheckBox.setSelected(false);
    }
    
    private void mostrarError(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje, "Validacion", JOptionPane.WARNING_MESSAGE);
    }
    
    private boolean validarCampos() {
        if (ipTxt.getText().trim().isEmpty()) {
            mostrarError("debes ingresar una direccion ip");
            return false;
        }
        if (numeroComputadoraTxt.getText().trim().isEmpty()) {
            mostrarError("debes ingresar un numero de computadora");
            return false;
        }
        if (laboratorioComboBox.getSelectedItem() == null
                || laboratorioComboBox.getSelectedItem().toString().equals("Selecciona...")) {
            mostrarError("Debes seleccionar un laboratorio");
            return false;
        }
        if (tipoComboBox1.getSelectedItem() == null
                || laboratorioComboBox.getSelectedItem().toString().equals("Selecciona...")) {
            mostrarError("Debes seleccionar un laboratorio");
            return false;
        }
        return true;
    }
    
    private NuevaComputadoraDTO construirNuevaComputadora() {
        String numero = numeroComputadoraTxt.getText().trim();
        String ip = ipTxt.getText().trim();
        EstatusComputadora estatus = EstatusComputadora.DISPONIBLE;
        String t = tipoComboBox1.getSelectedItem().toString();
        TipoComputadora tipo = TipoComputadora.fromString(t);
        String lab = laboratorioComboBox.getSelectedItem().toString();
        return new NuevaComputadoraDTO(numero, ip, estatus, tipo, lab);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AutoCadCheckBox;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JLabel ipLbl;
    private javax.swing.JTextField ipTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> laboratorioComboBox;
    private javax.swing.JLabel laboratorioLbl;
    private javax.swing.JLabel laboratorioLbl1;
    private javax.swing.JCheckBox mySqlCheckBox;
    private javax.swing.JCheckBox netBeansCheckBox;
    private javax.swing.JTextField numeroComputadoraTxt;
    private javax.swing.JLabel numeroLbl;
    private javax.swing.JCheckBox photoshopCheckBox;
    private javax.swing.JLabel softwareLbl;
    private javax.swing.JComboBox<String> tipoComboBox1;
    private javax.swing.JCheckBox wordCheckBox;
    // End of variables declaration//GEN-END:variables
}
