/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.Administrador;

import DTO.FiltroReporteCarrerasDTO;
import excepciones.NegocioException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import presentacion.reportes.Reporte;

/**
 *
 * @author saula
 */
public class PanelReporteCarreras extends javax.swing.JPanel {

    /**
     * Creates new form PanelReporteCarreras
     */
    public PanelReporteCarreras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        datePickerInicio = new com.github.lgooddatepicker.components.DatePicker();
        fechaFinLbl = new javax.swing.JLabel();
        fechaInicioLbl = new javax.swing.JLabel();
        datePickerFin = new com.github.lgooddatepicker.components.DatePicker();
        carrerasLbl = new javax.swing.JLabel();
        softwareCheckBox = new javax.swing.JCheckBox();
        arquitecturaCheckBox = new javax.swing.JCheckBox();
        mecatronicaCheckBox = new javax.swing.JCheckBox();
        industrialCheckBox = new javax.swing.JCheckBox();
        diseñoGraficoCheckBox = new javax.swing.JCheckBox();

        PanelFondo.setBackground(new java.awt.Color(0, 109, 182));

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setText("REPORTE DE CARRERAS");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 109, 181));

        agregarBtn.setText("GENERAR REPORTE");
        agregarBtn.setBackground(new java.awt.Color(0, 153, 255));
        agregarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anterior.png"))); // NOI18N
        btnAnterior.setBackground(new java.awt.Color(186, 215, 235));

        fechaFinLbl.setText("FECHA FIN:");
        fechaFinLbl.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        fechaFinLbl.setForeground(new java.awt.Color(4, 109, 181));

        fechaInicioLbl.setText("FECHA INICIO:");
        fechaInicioLbl.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        fechaInicioLbl.setForeground(new java.awt.Color(4, 109, 181));

        carrerasLbl.setText("CARRERAS:");
        carrerasLbl.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        carrerasLbl.setForeground(new java.awt.Color(4, 109, 181));

        softwareCheckBox.setText("Ing. Software");
        softwareCheckBox.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        softwareCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        arquitecturaCheckBox.setText("Arquitectura");
        arquitecturaCheckBox.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        arquitecturaCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        mecatronicaCheckBox.setText("Ing. Mecatrónica");
        mecatronicaCheckBox.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        mecatronicaCheckBox.setForeground(new java.awt.Color(4, 109, 181));
        mecatronicaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mecatronicaCheckBoxActionPerformed(evt);
            }
        });

        industrialCheckBox.setText("Ing. Industrial");
        industrialCheckBox.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        industrialCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        diseñoGraficoCheckBox.setText("Diseño Gráfico");
        diseñoGraficoCheckBox.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        diseñoGraficoCheckBox.setForeground(new java.awt.Color(4, 109, 181));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diseñoGraficoCheckBox)
                                    .addComponent(mecatronicaCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(softwareCheckBox)
                                            .addComponent(arquitecturaCheckBox)
                                            .addComponent(industrialCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(fechaFinLbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(datePickerFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(fechaInicioLbl)
                                                .addGap(18, 18, 18)
                                                .addComponent(datePickerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carrerasLbl)
                                    .addComponent(jLabel1))))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaInicioLbl)
                            .addComponent(datePickerInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaFinLbl)
                            .addComponent(datePickerFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(carrerasLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(softwareCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arquitecturaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(industrialCheckBox)
                        .addGap(6, 6, 6)
                        .addComponent(mecatronicaCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diseñoGraficoCheckBox)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mecatronicaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mecatronicaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mecatronicaCheckBoxActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        try {
            FiltroReporteCarrerasDTO filtro = new FiltroReporteCarrerasDTO();

            if (datePickerInicio.getDate() == null || datePickerFin.getDate() == null) {
                JOptionPane.showMessageDialog(this, "Selecciona ambas fechas.");
                return;
            }

            Date inicio = convertirLocalDateADate(datePickerInicio.getDate());
            Date fin = convertirLocalDateADate(datePickerFin.getDate());

            if (inicio.after(fin)) {
                JOptionPane.showMessageDialog(this, "La fecha de inicio no puede ser posterior a la fecha fin.");
                return;
            }
            filtro.setFechaInicio(inicio);
            filtro.setFechaFin(fin);

            //Carreras
            List<String> carreras = new ArrayList<>();
            if (softwareCheckBox.isSelected()) {
                carreras.add("Software");
            }
            if (diseñoGraficoCheckBox.isSelected()) {
                carreras.add("Diseño");
            }
            if (mecatronicaCheckBox.isSelected()) {
                carreras.add("Mecatronico");
            }
            if (industrialCheckBox.isSelected()) {
                carreras.add("Industrial");
            }
            if (arquitecturaCheckBox.isSelected()) {
                carreras.add("Arquitecto");
            }
            filtro.setCarreras(carreras);

            Reporte reporte = new Reporte();
            reporte.generarReporteCarreras(filtro);

        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarBtnActionPerformed

    private Date convertirLocalDateADate(LocalDate localDate) {
        return Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JCheckBox arquitecturaCheckBox;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JLabel carrerasLbl;
    private com.github.lgooddatepicker.components.DatePicker datePickerFin;
    private com.github.lgooddatepicker.components.DatePicker datePickerInicio;
    private javax.swing.JCheckBox diseñoGraficoCheckBox;
    private javax.swing.JLabel fechaFinLbl;
    private javax.swing.JLabel fechaInicioLbl;
    private javax.swing.JCheckBox industrialCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mecatronicaCheckBox;
    private javax.swing.JCheckBox softwareCheckBox;
    // End of variables declaration//GEN-END:variables
}
