/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion.Administrador;

import DTO.FiltroDTO;
import DTO.TablaLaboratorioDTO;
import excepciones.NegocioException;
import fachada.ILaboratorioFachada;
import fachada.implementaciones.LaboratorioFachada;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saula
 */
public class PanelConsultarLaboratorios extends javax.swing.JPanel {

    
    private final ILaboratorioFachada laboratorioFachada;
    private int offset = 0;
    private final int limite = 5;
    
    public PanelConsultarLaboratorios() {
        this.laboratorioFachada = new LaboratorioFachada();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buscadorTxt = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        agregarBtn = new javax.swing.JButton();
        btnPaginadoAnterior = new javax.swing.JButton();
        btnPaginadoSiguiente = new javax.swing.JButton();
        paginaLbl = new javax.swing.JLabel();
        modificarBtn = new javax.swing.JButton();

        PanelFondo.setBackground(new java.awt.Color(0, 109, 182));

        jPanel1.setBackground(new java.awt.Color(186, 215, 235));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.gray, java.awt.Color.darkGray));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 109, 181));
        jLabel1.setText("CONSULTAR LABORATORIOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "HORA APERTURA", "FECHAHORA CIERRE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnBuscar.setBackground(new java.awt.Color(0, 153, 255));
        btnBuscar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        agregarBtn.setBackground(new java.awt.Color(0, 153, 255));
        agregarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        agregarBtn.setText("AGREGAR");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        btnPaginadoAnterior.setBackground(new java.awt.Color(0, 153, 255));
        btnPaginadoAnterior.setText("Anterior");
        btnPaginadoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginadoAnteriorActionPerformed(evt);
            }
        });

        btnPaginadoSiguiente.setBackground(new java.awt.Color(0, 153, 255));
        btnPaginadoSiguiente.setText("Siguiente");
        btnPaginadoSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginadoSiguienteActionPerformed(evt);
            }
        });

        paginaLbl.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        paginaLbl.setForeground(new java.awt.Color(4, 109, 181));
        paginaLbl.setText("Página ");

        modificarBtn.setBackground(new java.awt.Color(0, 153, 255));
        modificarBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        modificarBtn.setText("MODIFICAR");
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(btnBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPaginadoAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPaginadoSiguiente)
                                .addGap(18, 18, 18)
                                .addComponent(paginaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                                .addComponent(agregarBtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificarBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPaginadoAnterior)
                            .addComponent(btnPaginadoSiguiente)
                            .addComponent(paginaLbl))
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout PanelFondoLayout = new javax.swing.GroupLayout(PanelFondo);
        PanelFondo.setLayout(PanelFondoLayout);
        PanelFondoLayout.setHorizontalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelFondoLayout.setVerticalGroup(
            PanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        abrirPanelAgregar();
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void btnPaginadoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginadoAnteriorActionPerformed
        if (offset - limite >= 0) {
            offset -= limite;
        } else {
            offset = 0;
        }
        try {
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPaginadoAnteriorActionPerformed

    private void btnPaginadoSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginadoSiguienteActionPerformed
        offset += limite;
        try {
            cargarTabla();
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los bloqueos: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnPaginadoSiguienteActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleciona una fila");
            return;
        }

        if (filaSeleccionada != -1) {
            int idBloqueo = (int) jTable1.getValueAt(filaSeleccionada, 0);
            try {
                laboratorioFachada.buscarPorId(idBloqueo);
                abrirPanelModificar();
            } catch (NegocioException ex) {
                JOptionPane.showMessageDialog(this, "error al abrir la ventana");
            }
        }
    }//GEN-LAST:event_modificarBtnActionPerformed

    
    private void cargarTabla() throws NegocioException {
        try {
            String buscador = buscadorTxt.getText().trim();
            FiltroDTO filtro = new FiltroDTO(limite, offset, buscador);
            List<TablaLaboratorioDTO> laboratorios = laboratorioFachada.buscarTabla(filtro);

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            for (TablaLaboratorioDTO l : laboratorios) {
                Object[] fila = {
                    l.getIdLaboratorios(),
                    l.getNombre(),
                    l.getHoraInicio(),
                    l.getHoraFin()
                };
                modelo.addRow(fila);
            }
        } catch (NegocioException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar las computadoras: " + ex.getMessage());
        }
    }
    
    private void abrirPanelAgregar(){
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        PanelAgregarLaboratorio panel = new PanelAgregarLaboratorio();
        
        frame.getContentPane().removeAll();
        frame.getContentPane().add(panel, BorderLayout.CENTER);
        frame.revalidate();
        frame.repaint();
    }

    public void abrirPanelModificar() {
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        PanelModificarLaboratorio panel = new PanelModificarLaboratorio();

        frame.getContentPane().removeAll();
        frame.getContentPane().add(panel, BorderLayout.CENTER);
        frame.revalidate();
        frame.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnPaginadoAnterior;
    private javax.swing.JButton btnPaginadoSiguiente;
    private javax.swing.JTextField buscadorTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JLabel paginaLbl;
    // End of variables declaration//GEN-END:variables
}
